# Generated by Django 4.2.17 on 2024-12-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpPartField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название картинки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='help_cases/')),
                ('date_field', models.DateField()),
            ],
        ),
    ]
